"""empty message

Revision ID: 3cb122151e9
Revises: None
Create Date: 2014-10-24 11:14:51.412540

"""

# revision identifiers, used by Alembic.
revision = '3cb122151e9'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_price_date'), 'price', ['date'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_price_date'), table_name='price')
    ### end Alembic commands ###
